GET http://localhost:9000

###
Post http://localhost:9000/user/create
Content-Type: application/json

{
    "email":"name9@provider.de",
    "password":"bB@123456",
    "userName":"Mongo",
    "avatar":"MongoPic"
}
### GET ALL Users
GET http://localhost:9000/usersList

###
POST http://localhost:9000/user/login
Content-Type: application/json

{
    "email":"rthyssen73@gmail.com",
    "password":"aA@123456"
}
###
PUT http://localhost:9000/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjhjYjRhYjA3YTE0MTMxYjE5NTBjN2UiLCJpYXQiOjE2NTMzOTMzOTh9.RPyWOHOly0i5VEcISIHcVfFjXF7VhKRYK9_SFDdlbeQ

###
GET http://localhost:9000/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjhjYjRhYjA3YTE0MTMxYjE5NTBjN2UiLCJpYXQiOjE2NTMzOTMzOTh9.RPyWOHOly0i5VEcISIHcVfFjXF7VhKRYK9_SFDdlbeQ

###
PUT http://localhost:9000/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjhjYjRhYjA3YTE0MTMxYjE5NTBjN2UiLCJpYXQiOjE2NTMzOTMzOTh9.RPyWOHOly0i5VEcISIHcVfFjXF7VhKRYK9_SFDdlbeQ

{
    "email":"eumilienchen.de",
    "password":"123"
}